version: '2'
services:
  rcloud:
    image: mangothecat/rcloud-dev
    ports:
    - "8080:8080"
    volumes:
    - rcloud:/data/rcloud
    - rcloud.sol:/pkgs/rcloud.solr
  solr:
    image: mangothecat/rcloud-solr
